version: '3'

volumes:
   geoserver-data:

networks:
  proxy:
    external: true
  internal:
    external: false

services:
   geoserver:
      image: kartoza/geoserver:2.13.0
      build:
        context: .
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "80"
      restart: unless-stopped
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:80/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
      labels:
      - traefik.frontend.rule=Host:geoserver.rwandata.com
      - traefik.docker.network=proxy
      - traefik.port=80
      networks:
      - internal
      - proxy
